
// This file has been generated by the GUI designer. Do not modify.
namespace Tomboy.ExportToLaTeX
{
	public partial class ExportToLaTeXDialog
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Image image2;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblNotebook;

		private global::Gtk.ComboBox notebook_selector;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label lblOutputformat;

		private global::Gtk.ComboBox dropdownFormat;

		private global::Gtk.CheckButton checkHyperlinking;

		private global::Gtk.CheckButton checkIcelandic;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonExecute;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Tomboy.ExportToLaTeX.ExportToLaTeXDialog
			this.Name = "Tomboy.ExportToLaTeX.ExportToLaTeXDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Export notebook");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			// Internal child Tomboy.ExportToLaTeX.ExportToLaTeXDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Xpad = 13;
			this.image2.Ypad = 13;
			this.image2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Dialog);
			this.vbox3.Add (this.image2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox3.Add (this.fixed1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.vbox2.Add (this.fixed3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblNotebook = new global::Gtk.Label ();
			this.lblNotebook.Name = "lblNotebook";
			this.lblNotebook.Ypad = 3;
			this.lblNotebook.Xalign = 0f;
			this.lblNotebook.LabelProp = global::Mono.Unix.Catalog.GetString ("Notebook:");
			this.lblNotebook.WidthChars = 12;
			this.hbox3.Add (this.lblNotebook);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblNotebook]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.notebook_selector = global::Gtk.ComboBox.NewText ();
			this.notebook_selector.Name = "notebook_selector";
			this.hbox3.Add (this.notebook_selector);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.notebook_selector]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblOutputformat = new global::Gtk.Label ();
			this.lblOutputformat.Name = "lblOutputformat";
			this.lblOutputformat.Ypad = 2;
			this.lblOutputformat.Xalign = 0f;
			this.lblOutputformat.LabelProp = global::Mono.Unix.Catalog.GetString ("Output format:");
			this.lblOutputformat.WidthChars = 12;
			this.hbox4.Add (this.lblOutputformat);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblOutputformat]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.dropdownFormat = global::Gtk.ComboBox.NewText ();
			this.dropdownFormat.Name = "dropdownFormat";
			this.hbox4.Add (this.dropdownFormat);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.dropdownFormat]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.checkHyperlinking = new global::Gtk.CheckButton ();
			this.checkHyperlinking.TooltipMarkup = "By selecting this option, hyperlinking between notes will be preserved in the output file.";
			this.checkHyperlinking.CanFocus = true;
			this.checkHyperlinking.Name = "checkHyperlinking";
			this.checkHyperlinking.Label = global::Mono.Unix.Catalog.GetString ("Use hyperlinking (LaTeX only)");
			this.checkHyperlinking.Active = true;
			this.checkHyperlinking.DrawIndicator = true;
			this.checkHyperlinking.UseUnderline = true;
			this.vbox2.Add (this.checkHyperlinking);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.checkHyperlinking]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.checkIcelandic = new global::Gtk.CheckButton ();
			this.checkIcelandic.TooltipMarkup = "By selecting this option certain settings will be added to the beginning of the LaTeX file that are needed to parse special Icelandic letters.";
			this.checkIcelandic.CanFocus = true;
			this.checkIcelandic.Name = "checkIcelandic";
			this.checkIcelandic.Label = global::Mono.Unix.Catalog.GetString ("Use Icelandic language compatibility mode (LaTeX only)");
			this.checkIcelandic.Active = true;
			this.checkIcelandic.DrawIndicator = true;
			this.checkIcelandic.UseUnderline = true;
			this.vbox2.Add (this.checkIcelandic);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.checkIcelandic]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w15.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.WidthRequest = 10;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed2]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 2;
			w16.Expand = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(w1[this.hbox1]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Internal child Tomboy.ExportToLaTeX.ExportToLaTeXDialog.ActionArea
			global::Gtk.HButtonBox w18 = this.ActionArea;
			w18.Name = "dialog1_ActionArea";
			w18.Spacing = 10;
			w18.BorderWidth = ((uint)(5));
			w18.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w18[this.buttonCancel]));
			w19.Expand = false;
			w19.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonExecute = new global::Gtk.Button ();
			this.buttonExecute.CanFocus = true;
			this.buttonExecute.Events = ((global::Gdk.EventMask)(512));
			this.buttonExecute.Name = "buttonExecute";
			this.buttonExecute.UseUnderline = true;
			// Container child buttonExecute.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w24.LabelProp = global::Mono.Unix.Catalog.GetString ("_Execute");
			w24.UseUnderline = true;
			w21.Add (w24);
			w20.Add (w21);
			this.buttonExecute.Add (w20);
			this.AddActionWidget (this.buttonExecute, -8);
			global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w18[this.buttonExecute]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 465;
			this.DefaultHeight = 210;
			this.Show ();
		}
	}
}
